# Generated by Django 3.2.13 on 2022-05-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20220508_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='order',
        ),
    ]
