# Generated by Django 3.2.13 on 2022-05-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_itemlist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
